# NumPy

In [1]:
import numpy as np
a = np.zeros((4,7,7))
print(a)

[[[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]]


In [2]:
a.shape

(4, 7, 7)

In [3]:
np.ones((4,4,5))  # 4,5 repeated 4 times

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [4]:
np.full((4,4),'manish')

array([['manish', 'manish', 'manish', 'manish'],
       ['manish', 'manish', 'manish', 'manish'],
       ['manish', 'manish', 'manish', 'manish'],
       ['manish', 'manish', 'manish', 'manish']], dtype='<U6')

In [5]:
np.random.randint(1,5,(2,7))  # generates random numbers between 1 and 5(excluding) of size 2,7

array([[2, 2, 3, 1, 1, 3, 2],
       [2, 3, 3, 3, 2, 1, 4]])

In [6]:
# create numpy array from python list
a = [1,2,3,4,5]
z= np.array(a)

In [7]:
print(type(z),z.shape, z.ndim, z.size)

<class 'numpy.ndarray'> (5,) 1 5


In [8]:
z = np.random.randint(100,200,(5,3,4))

In [9]:
z.ndim

3

In [10]:
data = np.random.randint(10,100,(5,4))

In [11]:
data

array([[98, 72, 65, 42],
       [12, 47, 85, 82],
       [72, 10, 19, 66],
       [48, 71, 93, 35],
       [91, 86, 54, 11]])

In [12]:
data[[1,4]]

array([[12, 47, 85, 82],
       [91, 86, 54, 11]])

## Reshaping

In [13]:
data = np.arange(10)

In [14]:
print(data)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
new_data = data.reshape(2,5)

In [16]:
print(new_data)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [17]:
new_data.shape

(2, 5)

In [18]:
new_data.reshape(-1,2).shape  # -1 will derive the number of rows

(5, 2)

In [19]:
new_data.reshape(-1,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

## Splitting and Stacking

In [20]:
data = np.random.randint(10,100,(5,10))
print(data)

[[24 91 97 13 62 64 11 33 19 18]
 [35 36 31 43 36 89 82 33 44 16]
 [51 42 92 87 48 21 27 44 76 91]
 [86 17 51 74 47 53 60 42 27 94]
 [92 14 41 78 21 45 52 66 20 61]]


In [21]:
a,b = np.hsplit(data,[7])  # splits the data into two parts
                           # first 0 to 7(excluding)

In [22]:
a,b = np.hsplit(data,[2,])
print(a)
print("___________")
print(b)

[[24 91]
 [35 36]
 [51 42]
 [86 17]
 [92 14]]
___________
[[97 13 62 64 11 33 19 18]
 [31 43 36 89 82 33 44 16]
 [92 87 48 21 27 44 76 91]
 [51 74 47 53 60 42 27 94]
 [41 78 21 45 52 66 20 61]]


In [23]:
print(a)
print("____________")
print(b)

[[24 91]
 [35 36]
 [51 42]
 [86 17]
 [92 14]]
____________
[[97 13 62 64 11 33 19 18]
 [31 43 36 89 82 33 44 16]
 [92 87 48 21 27 44 76 91]
 [51 74 47 53 60 42 27 94]
 [41 78 21 45 52 66 20 61]]


In [24]:
a,b = np.vsplit(data, [2])  # splits vertically
                            # it will split from 2 

In [25]:
print(a)
print("____________")
print(b)

[[24 91 97 13 62 64 11 33 19 18]
 [35 36 31 43 36 89 82 33 44 16]]
____________
[[51 42 92 87 48 21 27 44 76 91]
 [86 17 51 74 47 53 60 42 27 94]
 [92 14 41 78 21 45 52 66 20 61]]


In [26]:
np.vsplit(data, [3,4])

[array([[24, 91, 97, 13, 62, 64, 11, 33, 19, 18],
        [35, 36, 31, 43, 36, 89, 82, 33, 44, 16],
        [51, 42, 92, 87, 48, 21, 27, 44, 76, 91]]),
 array([[86, 17, 51, 74, 47, 53, 60, 42, 27, 94]]),
 array([[92, 14, 41, 78, 21, 45, 52, 66, 20, 61]])]

In [27]:
a = np.random.randint(10,100,(5,4))
print(a)

[[65 41 30 97]
 [81 35 14 62]
 [95 35 31 13]
 [36 22 24 88]
 [48 58 81 54]]


In [28]:
b = np.random.randint(10,100,(5,6))

In [29]:
print(b)

[[11 27 15 25 72 60]
 [45 92 39 27 23 45]
 [83 86 86 67 60 91]
 [63 92 16 81 62 83]
 [17 77 53 47 42 57]]


In [30]:
c = np.hstack([a,b])

In [31]:
c

array([[65, 41, 30, 97, 11, 27, 15, 25, 72, 60],
       [81, 35, 14, 62, 45, 92, 39, 27, 23, 45],
       [95, 35, 31, 13, 83, 86, 86, 67, 60, 91],
       [36, 22, 24, 88, 63, 92, 16, 81, 62, 83],
       [48, 58, 81, 54, 17, 77, 53, 47, 42, 57]])

In [32]:
a = np.random.randint(10,100,(5,4))
print(a)
b = np.random.randint(10,100,(10,4))
print(b)

[[89 37 83 93]
 [33 27 68 13]
 [88 15 20 90]
 [84 78 72 65]
 [54 66 39 97]]
[[71 28 39 96]
 [44 28 59 34]
 [96 42 60 31]
 [17 71 84 52]
 [97 27 91 43]
 [55 99 64 24]
 [44 26 56 72]
 [92 87 87 21]
 [78 10 15 91]
 [54 90 44 15]]


In [33]:
c = np.vstack([b,a])
print(c)

[[71 28 39 96]
 [44 28 59 34]
 [96 42 60 31]
 [17 71 84 52]
 [97 27 91 43]
 [55 99 64 24]
 [44 26 56 72]
 [92 87 87 21]
 [78 10 15 91]
 [54 90 44 15]
 [89 37 83 93]
 [33 27 68 13]
 [88 15 20 90]
 [84 78 72 65]
 [54 66 39 97]]


## Utilities

In [34]:
data = np.random.randint(1,100,(5,5))
data.max()

91

In [35]:
data = np.random.randint(1,100,20)
max(data)

96

In [36]:
data = np.random.randint(1,100,(5,5))
print(data)

[[29 31 97 20 78]
 [83 31 64 59 21]
 [49 96 46 33 68]
 [ 6 20 18 32  6]
 [13  4 98 27 61]]


In [37]:
data.max(axis = 1)  # max across each row

array([97, 83, 96, 32, 98])

In [38]:
data.sum(axis = 1)

array([255, 258, 292,  82, 203])

In [48]:
data = np.array([-1,-1,-1])
data.any()

True

In [46]:
data.all()

False

In [49]:
np.choose([1,0,1,0,1,1], choices = ['cat','rat'])

array(['rat', 'cat', 'rat', 'cat', 'rat', 'rat'], dtype='<U3')

In [51]:
data = np.random.randint(-10,10,20)

In [52]:
data.nonzero()

(array([ 0,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19], dtype=int64),)

In [53]:
data

array([-7,  2,  0,  3,  1,  1,  1, -6,  5,  2,  2, -9,  1,  7,  4, -9,  6,
        2, -8, -6])

In [55]:
data[np.where(data>0)]  # returns values > 0

array([2, 3, 1, 1, 1, 5, 2, 2, 1, 7, 4, 6, 2])

In [56]:
data[data>0]

array([2, 3, 1, 1, 1, 5, 2, 2, 1, 7, 4, 6, 2])

In [57]:
data[np.where(data<=0)]

array([-7,  0, -6, -9, -9, -8, -6])

In [58]:
data = np.random.randint(1,10,(4,4))
print(data)

[[4 9 6 7]
 [6 5 9 7]
 [7 8 9 9]
 [4 2 7 5]]


In [59]:
np.where(data>5)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2, 2, 3], dtype=int64),
 array([1, 2, 3, 0, 2, 3, 0, 1, 2, 3, 2], dtype=int64))

In [60]:
np.where((data>5)&(data<8))

(array([0, 0, 1, 1, 2, 3], dtype=int64),
 array([2, 3, 0, 3, 0, 2], dtype=int64))

In [61]:
data = np.random.randint(1,1000,100)
print(data)

[ 69 960 640 545 144 413 215 850 977 992 359  61 799 437 301 876 133 650
 373  10 365 671 767 152 316 261  10 814 619 854 893 903 613 273 348 551
 169 465  17 267 901 722 523 256 294  90 658  77 653 755 397 117 186 285
 535 898 353 829 197 587 326 833 451 499 158 409 289 476 645 327 577 346
 516 121 546 386 570 690 928 347 999 629 253 623 672 309 925 661 145 100
 178 691 787 413 834 471 399  62  92 926]


In [62]:
np.where(data > np.log2(data)*10)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 20, 21, 22, 23, 24, 25, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
        54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
        71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
        88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99], dtype=int64),)

In [67]:
len(data[np.where(data>np.log2(data)*10)])

97

In [2]:
data = np.random.randint(-10,10,20)

In [3]:
data

array([ -2,   9,   8, -10,   3,   6,  -3,   9,   8,   0,   7,   9,  -6,
         2,   2,   6,  -4,  -4,  -3,  -2])

## Statistics

In [2]:
data = np.random.randint(10,100,20)

In [3]:
data.mean()

54.25

In [5]:
np.median(data)

53.0

In [6]:
np.std(data)

23.05834989759675

In [7]:
data.std()

23.05834989759675

In [9]:
data.var()

531.6875

In [10]:
np.var(data)

531.6875

## Broadcasting

In [11]:
data1 = np.random.randint(1,100,(4,4))

In [12]:
data2 = np.random.randint(1,50,(4,2))

In [13]:
print(data1, data2)

[[89 25 94 54]
 [65  9 45 14]
 [42 46 80  5]
 [49 85 16 91]] [[ 4 20]
 [ 3 27]
 [26 18]
 [40 43]]


In [14]:
data1 + data2

ValueError: operands could not be broadcast together with shapes (4,4) (4,2) 

In [15]:
Mdata = np.array([[1,2,2],[5,2,1],[3,4,2]])
Ndata = np.array([[3,1,2],[1,4,1]])
print(Mdata.shape, Ndata.shape)

(3, 3) (2, 3)


In [17]:
Mdata = Mdata.reshape(3,1,3)
Ndata = Ndata.reshape(1,2,3)
print(Mdata.shape, Ndata.shape)

(3, 1, 3) (1, 2, 3)


In [18]:
Mdata - Ndata

array([[[-2,  1,  0],
        [ 0, -2,  1]],

       [[ 2,  1, -1],
        [ 4, -2,  0]],

       [[ 0,  3,  0],
        [ 2,  0,  1]]])

In [19]:
Mdata.reshape(3,1,3)-Ndata.reshape(1,2,3)

array([[[-2,  1,  0],
        [ 0, -2,  1]],

       [[ 2,  1, -1],
        [ 4, -2,  0]],

       [[ 0,  3,  0],
        [ 2,  0,  1]]])